# Change these first
owner: BobChrismansyah # Your GitHub organization or username, where this repository lives
repo: monitor-serverbob # The name of this repository

sites:
  - name: ServerBob
    url: https://proxmox.notsec.site
 #   port: 80
 #   check: "tcp-ping"
 #   ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: bobchrismansyah.github.io/monitoring-serverbob/
  theme: dark
  name: serverbob
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  introTitle: "**Upptime** ServerBob"
  introMessage: Testing
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
